apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: {name: nsxerrors.nsx.vmware.com}
spec:
  additionalPrinterColumns:
  - {JSONPath: .spec.message, description: NSX error messages. Messages are sorted
      by timestamp on which the error occurs., name: Messages, type: string}
  - {JSONPath: .spec.error-object-id, description: The identifier of the k8s object
      which has the errors., name: ErrorObjectID, type: string}
  - {JSONPath: .spec.error-object-type, description: The type of the k8s object which
      has the errors., name: ErrorObjectType, type: string}
  - {JSONPath: .spec.error-object-name, description: The name of the k8s object which
      has the errors., name: ErrorObjectName, type: string}
  - {JSONPath: .spec.error-object-ns, description: The namespace of the k8s object
      if it is namespaced. None by default, name: ErrorObjectNamespace, type: string}
  group: nsx.vmware.com
  names:
    kind: NSXError
    plural: nsxerrors
    shortNames: [ne]
    singular: nsxerror
  scope: Cluster
  version: v1
  versions:
  - {name: v1, served: true, storage: true}
