apiVersion: v1
data: {ncp.ini: '


    [DEFAULT]


    #debug = False


    [k8s]

    apiserver_host_ip = api.ocp.yasen.local

    apiserver_host_port = 6443

    client_token_file = /var/run/secrets/kubernetes.io/serviceaccount/token


    ca_file = /var/run/secrets/kubernetes.io/serviceaccount/ca.crt


    loglevel = WARNING


    [coe]

    adaptor = openshift4

    cluster = ocp

    loglevel = WARNING

    nsxlib_loglevel = WARNING

    node_type = HOSTVM


    [nsx_kube_proxy]

    config_handler = ovs


    [nsx_node_agent]


    ovs_bridge = br-int

    ovs_uplink_port = ens192


    #use_nsx_ovs_kernel_module = False


    #enable_ipv6 = False



    '}
kind: ConfigMap
metadata:
  labels: {version: v1}
  name: nsx-node-agent-config
  namespace: nsx-system
