apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: {name: nsxlocks.nsx.vmware.com}
spec:
  group: nsx.vmware.com
  names:
    kind: NSXLock
    plural: nsxlocks
    shortNames: [nsxlo]
    singular: nsxlock
  scope: Cluster
  version: v1
  versions:
  - {name: v1, served: true, storage: true}
