apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: {name: ncp-cluster-role-binding}
roleRef: {kind: ClusterRole, name: ncp-cluster-role}
subjects:
- {kind: ServiceAccount, name: ncp-svc-account, namespace: nsx-system}
