apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: {name: ncpconfigs.nsx.vmware.com}
spec:
  group: nsx.vmware.com
  names:
    kind: NCPConfig
    plural: ncpconfigs
    shortNames: [ncpcfg]
    singular: ncpconfig
  scope: Cluster
  version: v1
  versions:
  - {name: v1, served: true, storage: true}
